### ISSUE TITLE
Support Clojure 1.9 clj tool

### ISSUE THREAD

**Issue by saulshanabrook** [jgpc42/jmh-clojure#5]
Clojure 1.9 was just released with the addition of the `clj` command line tool. It let's you declare dependencies in and start a repl or run a `-main` entrypoint ([guide](https://clojure.org/guides/deps_and_cli)). 

I am just getting started with `lein-jmh`, but am now wondering about switching away from Leiningen entirely, now that this tool has been released. Do you have any thoughts on how much work it would be to use this library with that tool?

**Comment by jgpc42** [comment]
Since `lein-jmh` is mostly a thin wrapper for this library, I don't anticipate any problems. However, I haven't yet familiarized myself with the `clj` tool. I'll check out the guide when I get a chance and get back to you.

I did write a short wiki [entry](https://github.com/jgpc42/jmh-clojure/wiki/Bare-REPL) that outlines the simple steps necessary to run without Leiningen (or [Boot](https://github.com/boot-clj/boot), etc.). I don't know if this is relevant, however.

Thanks for the heads up!

**Comment by jgpc42** [comment]
As expected, there is no problem running via these tools. I made a new [wiki page](https://github.com/jgpc42/jmh-clojure/wiki/Clojure-1.9-CLI) that details the process of running via `clj`.

Thanks again @saulshanabrook for bringing this up!

**Comment by saulshanabrook** [comment]
@jgpc42 Thank you for adding that documentation! 

It looks like I was a little eager to switch to the tool, [there are some other roadblocks in our way first](https://github.com/lspector/Clojush/issues/242).
